### ISSUE TITLE
Consolidate Batch, Inserter, Query, Scan, and Update Query into a single class

### ISSUE THREAD

**Issue by imlucas** [imlucas/node-mambo#40]
## From previous ticket 

Already sort of doing this in a few places, but would be nice to be able to specify just the units per sec and do all of the nice calculation / automatic page sizing under the hood.

http://java.awsblog.com/post/Tx3VAYQIZ3Q0ZVW/Rate-Limited-Scans-in-Amazon-DynamoDB

**Comment by imlucas** [comment]
This also means scan will get proper paging support like Query

**Comment by majman** [comment]
yeah, bitches
